site_name: Summer School Course

extra_css:
  - css/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

plugins:
  - glightbox

theme:
  name: material

  features:
    - header.autohide
    - navigation.sections
    # - navigation.expand

  font:
    text: Gelasio # Serif: Gelasio
    code: Roboto Mono

  palette:
    # - primary: glue grey
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  generator: false
